apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-canary
spec:
  selector:
    matchLabels:
      app: strimzi-canary
  template:
    metadata:
      labels:
        app: strimzi-canary
    spec:
      containers:
      - name: strimzi-canary
        image: quay.io/ppatierno/strimzi-canary:tls-test
        imagePullPolicy: Always
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9094
          - name: RECONCILE_INTERVAL_MS
            value: "5000"
          - name: EXPECTED_CLUSTER_SIZE
            value: "3"
          - name: VERBOSITY_LOG_LEVEL
            value: "1"
          - name: SARAMA_LOG_ENABLED
            value: "true"
          - name: TLS_ENABLED
            value: "true"
          - name: TLS_CA_CERT
            value: "/tmp/tls-ca-cert/ca.crt"
          - name: TLS_CLIENT_CERT
            value: "/tmp/tls-canary-user-cert/user.crt"
          - name: TLS_CLIENT_KEY
            value: "/tmp/tls-canary-user-cert/user.key"   
        volumeMounts:
          - mountPath: /tmp/tls-ca-cert
            name: tls-ca-cert
          - mountPath: /tmp/tls-canary-user-cert
            name: tls-canary-user-cert 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: tls-ca-cert
        secret:
          secretName: my-cluster-cluster-ca-cert  
      - name: tls-canary-user-cert
        secret:
          secretName: canary-user
