jobs:
- job: container_push
  displayName: Container Push
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # step for Docker installation  
  - template: ../steps/setup_docker.yaml
  - task: DownloadPipelineArtifact@2
    inputs:
      source: '${{ parameters.artifactSource }}'
      artifact: Container
      path: $(System.DefaultWorkingDirectory)
      project: '${{ parameters.artifactProject }}'
      pipeline: '${{ parameters.artifactPipeline }}'
      runVersion: '${{ parameters.artifactRunVersion }}'
      runId: '${{ parameters.artifactRunId }}'
  - bash: .azure/scripts/container-push.sh
    displayName: Docker Push
    env:
      DOCKER_USER: $(QUAY_USER)
      DOCKER_PASS: $(QUAY_PASS)
      DOCKER_REGISTRY: quay.io
      DOCKER_ORG: strimzi
      DOCKER_TAG: '${{ parameters.dockerTag }}'
