jobs:
- job: container_build
  displayName: Container Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # step for Docker installation
  - template: ../steps/setup_docker.yaml
  - task: DownloadPipelineArtifact@2
    inputs:
      source: '${{ parameters.artifactSource }}'
      artifact: Binary
      path: $(System.DefaultWorkingDirectory)/
      project: '${{ parameters.artifactProject }}'
      pipeline: '${{ parameters.artifactPipeline }}'
      runVersion: '${{ parameters.artifactRunVersion }}'
      runId: '${{ parameters.artifactRunId }}'
  - bash: tar -xvf target.tar
    displayName: "Untar the target directory"        
  - bash: .azure/scripts/container-build.sh
    displayName: Docker Build & Save
    env:
      BUILD_REASON: $(Build.Reason)
      BRANCH: $(Build.SourceBranch)
      DOCKER_REGISTRY: quay.io
      DOCKER_ORG: strimzi
  - publish: $(System.DefaultWorkingDirectory)/canary-container.tar.gz
    displayName: Publish container
    artifact: Container