trigger: 
  branches:
    include:
    - 'main'

pr:
  autoCancel: true
  branches:
    include:
    - '*'

stages:
- stage: go_build
  displaName: Go tests and build
  jobs:
  - job: go_tests_and_build
    displayName: Test & Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.16.3'
    - task: Go@0
      displayName: Go Unit Tests
      inputs:
        command: test
        arguments: ./internal/... --tags=unit_test
    - bash: "make go_build"
      displayName: Go Build
    - publish: $(Build.SourcesDirectory)/cmd/target
      displayName: Publish binary
- stage: go_e2e_test
  displaName: Go e2e tests
  jobs:
  - job: go_e2e_tests
    display: Go e2e tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.16.3'
    - task: Go@0
      displayName: Go e2e Tests
      inputs:
        command: test
        arguments: ./test/... --tags=e2e