trigger: 
  branches:
    include:
      - 'main'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

stages:
- stage: go_test
  displayName: Go Test
  jobs:
  - job: go_test
    displayName: Go Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: "go test ./internal/... --tags=unit_test"
      displayName: Go Unit Tests
    - bash: "go test ./test/... --tags=e2e"
      displayName: Go E2E Tests   
- stage: go_build
  displayName: Go
  jobs:
  - job: go_build
    displayName: Go Build
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: GoTool@0
      inputs:
        version: '1.16.3'
    - bash: "make go_build"
      displayName: Go build
    - publish: $(Build.SourcesDirectory)/cmd/target
      displayName: Publish binary