trigger: 
  branches:
    include:
    - 'main'

pr:
  autoCancel: true
  branches:
    include:
    - '*'

stages:
- stage: go_test
  displayName: Go Test
  jobs:
  - job: go_test
    displayName: Go Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # step for Go installation
    - template: ./templates/steps/setup_go.yaml
    - task: Go@0
      displayName: Go Unit Tests
      inputs:
        command: test
        arguments: ./internal/... --tags=unit_test
    - task: Go@0
      displayName: Go e2e Tests
      inputs:
        command: test
        arguments: ./test/... --tags=e2e
- stage: go_build
  displayName: Go Build
  dependsOn:
  - go_test
  jobs:
  - job: go_build
    displayName: Go Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # step for Go installation
    - template: ./templates/steps/setup_go.yaml
    - bash: make go_build
      displayName: Go Build
    # We have to TAR the target directory to maintain the permissions of 
    # the files which would otherwise change when downloading the artifact
    - bash: tar -cvpf target.tar ./cmd/target
      displayName: "Tar the target directory"      
    - publish: $(System.DefaultWorkingDirectory)/target.tar
      displayName: Publish binary
      artifact: Binary
- stage: container_build
  displayName: Prepare Container
  dependsOn:
  - go_build
  jobs:
  - template: ./templates/jobs/container_build.yaml
    parameters:
      artifactSource: 'current'
      artifactProject: 'strimzi'
      artifactPipeline: ''
      artifactRunVersion: ''
      artifactRunId: ''
- stage:
  displayName: Publish Container
  dependsOn:
  - container_build
  condition: and(succeeded(), eq(variables['Build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: container_push
    displayName: Container Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # step for Docker installation  
    - template: ./templates/steps/setup_docker.yaml
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: Container
        path: $(System.DefaultWorkingDirectory)
    - bash: .azure/scripts/container-push.sh
      displayName: Docker Push
      env:
        DOCKER_REGISTRY: quay.io
        DOCKER_ORG: strimzi
        DOCKER_TAG: latest
        DOCKER_USER: $(QUAY_USER)
        DOCKER_PASS: $(QUAY_PASS)