trigger: none
pr: none

parameters:
- name: releaseVersion
  displayName: Release Version
  type: string
- name: useSuffix
  displayName: Build suffixed images
  type: boolean
  default: true
- name: releaseSuffix
  displayName: Release Suffix
  type: number
- name: sourcePipelineId
  displayName: Pipeline ID of the source build
  type: number
  default: 42
  values:
  - 42
- name: sourceBuildId
  displayName: Build ID of the source build
  type: number

stages:
- stage: release_artifacts
  displayName: Release artifacts for ${{ parameters.releaseVersion }}
  condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release-')
  jobs:
  - job: release_artifacts
    displayName: Release Artifacts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: .azure/scripts/release-artifacts.sh
      env:
        BUILD_REASON: $(Build.Reason)
        BRANCH: $(Build.SourceBranch)
        RELEASE_VERSION: '${{ parameters.releaseVersion }}'
      displayName: Prepare release artifacts
    - publish: $(System.DefaultWorkingDirectory)/strimzi-canary-${{ parameters.releaseVersion }}.tar.gz
      artifact: ReleaseTarGzArchive
    - publish: $(System.DefaultWorkingDirectory)/strimzi-canary-${{ parameters.releaseVersion }}.zip
      artifact: ReleaseZipArchive
- stage: containers_publish_with_suffix
  displayName: Publish Containers for ${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}
  dependsOn: 
  - release_artifacts
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
  jobs:
  - template: ./templates/jobs/container_push.yaml
    parameters:
      dockerTag: '${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}'
      artifactSource: 'specific'
      artifactProject: 'strimzi'
      artifactPipeline: '${{ parameters.sourcePipelineId }}'
      artifactRunVersion: 'specific'
      artifactRunId: '${{ parameters.sourceBuildId }}'
- stage: containers_publish
  displayName: Publish Containers for ${{ parameters.releaseVersion }}
  dependsOn: 
  - release_artifacts
  - containers_publish_with_suffix
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
  jobs:
  - template: ./templates/jobs/container_push.yaml
    parameters:
      dockerTag: '${{ parameters.releaseVersion }}'
      artifactSource: 'specific'
      artifactProject: 'strimzi'
      artifactPipeline: '${{ parameters.sourcePipelineId }}'
      artifactRunVersion: 'specific'
      artifactRunId: '${{ parameters.sourceBuildId }}'     
